//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHoiDap {
    
    
    public partial class TrangCaNhan {
        
        /// <summary>
        /// idThongTinTaiKhoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteHoiDap.Controls.ucThongTinTaiKhoan idThongTinTaiKhoan;
        
        /// <summary>
        /// idDSCauHoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteHoiDap.Controls.ucDSCauHoiCuaThanhVien idDSCauHoi;
        
        /// <summary>
        /// idDSCauTraLoi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteHoiDap.Controls.ucDSCauTraLoiCuaThanhVien idDSCauTraLoi;
        
        /// <summary>
        /// idTop5ThanhVien control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteHoiDap.Controls.ucTop5ThanhVien idTop5ThanhVien;
    }
}
